[build]
# Enable colored output
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
# Useful aliases
t = "test"
c = "check"
b = "build"
r = "run"
